version: "3.8"

#Сервисы
services:

  database:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  web:
    container_name: web_container
    image: app
    depends_on:
      - database
    ports:
      - "1234:1234"
    environment:
      - DB_NAME=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - PORT=1234
      - DB_HOST=172.30.209.41
    restart: unless-stopped
