version: "3.8"

#Сервисы
services:

  database:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

    
